[package]
name = "jxl-transform"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
jxl-core = { path = "../jxl-core" }
num-traits.workspace = true
lazy_static = "1.4"
